import json
import os
import re

# Path to the source JS file
JS_FILE_PATH = os.path.join(os.path.dirname(__file__), '..', '..', 'device_data.js')
# Path to the output JSON file
JSON_OUTPUT_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'device_data.json')

def convert_js_to_json():
    """
    Reads device_data.js (which contains a JS object literal) and converts it to valid JSON.
    """
    if not os.path.exists(JS_FILE_PATH):
        print(f"Source file not found: {JS_FILE_PATH}")
        return

    print(f"Reading {JS_FILE_PATH}...")
    with open(JS_FILE_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract the object content. 
    # Assumes format: const extractedDeviceDatabase = { ... };
    # We need to find the first { and the last };
    
    start_idx = content.find('{')
    end_idx = content.rfind('};')
    
    if start_idx == -1 or end_idx == -1:
        print("Could not parse JS object structure.")
        return

    json_str = content[start_idx:end_idx+1]
    
    # Simple heuristic to convert JS object keys to strict JSON
    # This might need adjustment if the JS is complex, but for the generated file it should work.
    # However, device_data.js is ALREADY generated by extract_data.py using json.dumps!
    # extract_data.py line 108: js_content = f"const extractedDeviceDatabase = {json.dumps(all_devices, indent=2)};"
    # So the content between { and } IS valid JSON (except for the outer variable assignment).
    
    # Actually, json.dumps outputs a dictionary, so it starts with { and ends with }.
    # So we just need to strip the prefix.
    
    # However, all_devices is a Dict[Key, Dict].
    # The sample JSON I created is a List[Dict].
    # The backend expects List[Dict] in ExcelLoader?
    # Let's check ExcelLoader. It returns List[Dict].
    # But device_data.js is a Dict (Key -> Object).
    # We should convert it to a List of Objects for the backend to iterate easily, 
    # OR update ClassificationService to handle Dict.
    # ClassificationService uses: `self.data_map = {d.get('originalName', '').lower(): d for d in self.device_data}`
    # and `fuzzy_result = self.embedding_service.find_best_match(device_name, self.device_data)`
    # This implies self.device_data is a LIST.
    
    # So this converter should convert the Dict to a List.
    
    try:
        data_dict = json.loads(json_str)
        data_list = list(data_dict.values())
        
        print(f"Extracted {len(data_list)} devices.")
        
        with open(JSON_OUTPUT_PATH, 'w', encoding='utf-8') as f:
            json.dump(data_list, f, indent=2)
            
        print(f"Successfully saved to {JSON_OUTPUT_PATH}")
        
    except json.JSONDecodeError as e:
        print(f"JSON Decode Error: {e}")

if __name__ == "__main__":
    convert_js_to_json()
